"""OWB-S107a — CI drift check for the committed example SBOM.

AC 8: ``examples/sbom/example.cdx.json`` is regenerated by this test on
every run and must match the committed copy byte-for-byte. When this test
fails, run::

    python -m open_workspace_builder.sbom._example

to regenerate the fixture, review the diff, and commit.
"""

from __future__ import annotations

from open_workspace_builder.sbom._example import (
    EXAMPLE_SBOM_PATH,
    regenerate_example_sbom,
)


class TestExampleSbomDriftCheck:
    def test_committed_example_is_up_to_date(self) -> None:
        assert EXAMPLE_SBOM_PATH.is_file(), (
            f"Missing committed example SBOM at {EXAMPLE_SBOM_PATH}. "
            "Run: python -m open_workspace_builder.sbom._example"
        )
        committed = EXAMPLE_SBOM_PATH.read_text(encoding="utf-8")
        regenerated = regenerate_example_sbom()
        assert committed == regenerated, (
            "Example SBOM has drifted from regeneration. "
            "This means either the fixture workspace at "
            "tests/fixtures/sbom-example/ was modified, or the SBOM builder "
            "output shape changed. Review the diff and, if intentional, "
            "regenerate the committed copy with:\n\n"
            "    python -m open_workspace_builder.sbom._example\n"
        )

    def test_committed_example_is_valid_cyclonedx(self) -> None:
        from cyclonedx.schema import SchemaVersion
        from cyclonedx.validation.json import JsonStrictValidator

        committed = EXAMPLE_SBOM_PATH.read_text(encoding="utf-8")
        validator = JsonStrictValidator(SchemaVersion.V1_6)
        errors = validator.validate_str(committed)
        assert errors is None, f"Committed example is not valid CycloneDX 1.6: {errors}"
