"""Hook-based policy enforcement (OWB-S067).

Provides:
- Policy manifest generation from a policies directory
- Hook script deployment for Claude Code UserPromptSubmit hooks
- Hook registration/removal in .claude/settings.json
"""

from __future__ import annotations

import json
import stat
import textwrap
from pathlib import Path
from typing import Any

import yaml

from open_workspace_builder.config import Config

# Files excluded from the manifest (not user-facing policies)
_EXCLUDED_FILES = {"_index.md", "readme.md"}

_HOOK_SCRIPT_TEMPLATE = textwrap.dedent("""\
    #!/usr/bin/env bash
    # OWB Policy Enforcement Hook
    # Auto-generated by open-workspace-builder. Do not edit manually.
    # Fires on UserPromptSubmit to re-inject policy reminders.

    MANIFEST="{manifest_path}"

    if [ ! -f "$MANIFEST" ]; then
        exit 0
    fi

    echo "[OWB Policy Reminder] The following policies govern this workspace."
    echo "Read the full document before making decisions in that domain."

    # Parse YAML manifest and emit policy list
    # Uses grep -F (fixed string) for portability and safety
    grep -E "^  - path:" "$MANIFEST" | while IFS= read -r line; do
        path=$(echo "$line" | sed 's/.*path: *//')
        # Find the matching summary line (next line after path)
        summary=$(grep -F -A1 "path: $path" "$MANIFEST" | grep "summary:" | sed 's/.*summary: *"//' | sed 's/"$//')
        echo "- $path: $summary"
    done
""")


def _extract_summary(policy_path: Path) -> str:
    """Extract a one-line summary from a policy file.

    Uses the first non-heading, non-empty line as the summary.
    Falls back to the H1 heading text if no body content found.
    """
    lines = policy_path.read_text(encoding="utf-8").splitlines()
    heading = ""
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("# "):
            heading = stripped.lstrip("# ").strip()
            continue
        if stripped.startswith("#"):
            continue
        if stripped.startswith("---"):
            continue
        # First non-heading, non-empty, non-frontmatter line
        return stripped[:120]
    return heading[:120] if heading else policy_path.stem


def generate_manifest(policies_dir: Path, output_path: Path) -> None:
    """Scan a policies directory and write a policy-manifest.yaml.

    Skips _index.md and readme.md. Sorts entries alphabetically by filename.
    """
    entries: list[dict[str, str]] = []

    if policies_dir.is_dir():
        for policy_file in sorted(policies_dir.iterdir()):
            if not policy_file.is_file():
                continue
            if policy_file.name.lower() in _EXCLUDED_FILES:
                continue
            if not policy_file.name.endswith(".md"):
                continue
            summary = _extract_summary(policy_file)
            entries.append({"path": policy_file.name, "summary": summary})

    manifest = {"policies": entries}
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        yaml.dump(manifest, default_flow_style=False, sort_keys=False),
        encoding="utf-8",
    )


def deploy_hooks(
    config: Config,
    policies_dir: Path,
    owb_dir: Path,
    agent_config_dir: Path,
) -> None:
    """Deploy hook script, manifest, and settings.json entry.

    Only deploys when enforcement.hooks_enabled is True and stage >= 1.
    """
    if not config.enforcement.hooks_enabled:
        return
    if config.stage.current_stage < 1:
        return

    # Generate manifest
    manifest_path = owb_dir / "policy-manifest.yaml"
    generate_manifest(policies_dir=policies_dir, output_path=manifest_path)

    # Deploy hook script
    hooks_dir = owb_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    script_path = hooks_dir / "policy-reminder.sh"
    script_content = _HOOK_SCRIPT_TEMPLATE.format(
        manifest_path=str(manifest_path.resolve()),
    )
    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    # Register in settings.json
    _register_hook(agent_config_dir=agent_config_dir, script_path=script_path)


def _register_hook(agent_config_dir: Path, script_path: Path) -> None:
    """Add UserPromptSubmit hook entry to settings.json."""
    agent_config_dir.mkdir(parents=True, exist_ok=True)
    settings_path = agent_config_dir / "settings.json"

    settings: dict[str, Any] = {}
    if settings_path.is_file():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            settings = {}

    hooks = settings.setdefault("hooks", {})
    hooks["UserPromptSubmit"] = [{"command": f"bash {script_path}"}]

    settings_path.write_text(
        json.dumps(settings, indent=2) + "\n",
        encoding="utf-8",
    )


def remove_hook_registration(agent_config_dir: Path) -> None:
    """Remove UserPromptSubmit hook entry from settings.json.

    Leaves the script and manifest files in place (inactive but preserved).
    """
    settings_path = agent_config_dir / "settings.json"
    if not settings_path.is_file():
        return

    try:
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return

    hooks = settings.get("hooks", {})
    if "UserPromptSubmit" not in hooks:
        return

    del hooks["UserPromptSubmit"]
    settings_path.write_text(
        json.dumps(settings, indent=2) + "\n",
        encoding="utf-8",
    )
